import {
  getTowerLevelStats,
  getUpgradeCost,
  MAX_TOWER_LEVEL,
  type TowerLevelStats,
  type TowerType,
} from "@/config/towerStats";
import {
  getSpecializationUpgradeCost,
  isSpecializationForTower,
  MAX_SPECIALIZATION_LEVEL,
  SPECIALIZATION_UNLOCK_TOWER_LEVEL,
  type SpecializationId,
} from "@/config/specializations";
import { getTowerSkinDefinition } from "@/config/towerSkins";
import { getTowerSpecialCooldownMs } from "@/config/towerSpecials";
import { getMasteryBonusMultipliers, getMasteryUpgradeCost } from "@/config/towerMastery";
import { getTowerSurvivalDefinition } from "@/config/towerSurvival";
import type { Vector2 } from "@/utils/geometry";

export interface TowerInstance {
  id: string;
  slotId: string;
  type: TowerType;
  level: number;
  position: Vector2;
  cooldownRemainingMs: number;
  /**
   * Master Implementation spec section 26-28 — Special Attack: a SECOND,
   * fully independent cooldown timer from `cooldownRemainingMs`. The normal
   * attack keeps firing at its attack-speed-driven cadence exactly as
   * before; this one ticks down on a fixed per-tower-type interval (see
   * config/towerSpecials.ts) and fires a distinct, more impactful attack
   * when it reaches 0, without ever touching or resetting the normal
   * cooldown. Deliberately NOT derived from attackSpeed — it's a rhythm of
   * its own, the way a real "ultimate" reads differently from a basic
   * attack.
   */
  specialCooldownRemainingMs: number;
  /** >0 while jammed by a DISABLER-archetype enemy/mini-boss — see CombatSystem.tickEnemyDisableAbilities. */
  disabledRemainingMs: number;
  /** Progression 2.0 — the player's chosen build-identity path, null until chosen. Permanent once set (see chooseSpecialization). */
  specializationId: SpecializationId | null;
  /** 0 = not chosen yet. 1..MAX_SPECIALIZATION_LEVEL once chosen — a second, independent gold-sink track from the tower's own level. */
  specializationLevel: number;
  /** Progression 2.0 — cosmetic-only equipped skin id, or null for the default look. Never read by combat code. */
  equippedSkinId: string | null;
  /** Master Implementation Pass spec section 4-6 — TOWER MASTERY: an uncapped, independent gold-sink track past MAX_TOWER_LEVEL. 0 = never invested. See config/towerMastery.ts for the bonus/cost formulas. */
  masteryLevel: number;

  // -------------------------------------------------------------------
  // Master Implementation Pass spec section 12-13 — TOWER SURVIVAL /
  // BOSS SIEGE ATTACK. Deliberately TRANSIENT (not part of
  // TowerLoadoutEntry / SaveData): a tower's current battle HP resets to
  // full on every retryPhase(), exactly like Castle HP already does (see
  // GameEngine.resetAttemptState) — never a lingering, unrecoverable
  // "damaged" state carried into a fresh attempt. Level/Mastery/
  // Specialization stay the only permanent parts of a tower.
  // -------------------------------------------------------------------
  hp: number;
  maxHp: number;
  /** 0 for a tower type with no shield identity (see config/towerSurvival.ts) — always <= its type's maxShield. */
  shieldHp: number;
}

/**
 * Persistent shape of a tower — what survives across attempts/reloads in
 * SaveData. Deliberately excludes runtime-only fields (id, position,
 * cooldown) that get regenerated by `createTowerInstance` on resume.
 */
export interface TowerLoadoutEntry {
  slotId: string;
  type: TowerType;
  level: number;
  /** Optional so existing fixtures/tests written before Progression 2.0 still typecheck — SaveSystem.parseTowerLoadout and GameEngine.persist() always populate these on real data. */
  specializationId?: SpecializationId | null;
  specializationLevel?: number;
  equippedSkinId?: string | null;
  /** Optional for the same reason as the specialization fields above — self-heals to 0 on load for a save written before Mastery existed. */
  masteryLevel?: number;
}

let nextTowerId = 1;

export function createTowerInstance(
  slotId: string,
  type: TowerType,
  position: Vector2,
  initialLevel = 1,
  specializationId: SpecializationId | null = null,
  specializationLevel = 0,
  equippedSkinId: string | null = null,
  masteryLevel = 0,
): TowerInstance {
  return {
    id: `tower-${nextTowerId++}`,
    slotId,
    type,
    level: Math.min(Math.max(initialLevel, 1), MAX_TOWER_LEVEL),
    position,
    cooldownRemainingMs: 0,
    // A freshly-built tower must charge up before its first Special Attack
    // — the ultimate meter starts empty, not full — both thematically (an
    // "ultimate" firing before a single normal shot feels wrong) and
    // mechanically (keeps the special's much bigger cooldown from ever
    // colliding with the normal attack's own instant-ready-at-0 on the
    // very same first tick).
    specialCooldownRemainingMs: getTowerSpecialCooldownMs(type),
    disabledRemainingMs: 0,
    specializationId,
    specializationLevel,
    equippedSkinId,
    masteryLevel,
    ...survivalStatsForFreshTower(type),
  };
}

function survivalStatsForFreshTower(type: TowerType): Pick<TowerInstance, "hp" | "maxHp" | "shieldHp"> {
  const def = getTowerSurvivalDefinition(type);
  return { hp: def.maxHp, maxHp: def.maxHp, shieldHp: def.maxShield };
}

/** Restores a tower's battle HP/shield to full — called once per tower at the start of every attempt (see GameEngine.resetAttemptState), the same "fresh attempt" treatment Castle HP already gets. */
export function resetTowerSurvival(tower: TowerInstance): void {
  const fresh = survivalStatsForFreshTower(tower.type);
  tower.hp = fresh.hp;
  tower.maxHp = fresh.maxHp;
  tower.shieldHp = fresh.shieldHp;
}

/** Flat HP/shield regeneration per second (Recovery — spec section 12), ticked every combat frame alongside tickTowerCooldown. */
export function tickTowerSurvivalRegen(tower: TowerInstance, dtMs: number): void {
  const def = getTowerSurvivalDefinition(tower.type);
  const dtSeconds = dtMs / 1000;
  if (def.maxShield > 0 && tower.shieldHp < def.maxShield) {
    tower.shieldHp = Math.min(def.maxShield, tower.shieldHp + def.shieldRegenPerSecond * dtSeconds);
  }
  if (tower.hp < tower.maxHp) {
    tower.hp = Math.min(tower.maxHp, tower.hp + def.hpRegenPerSecond * dtSeconds);
  }
}

export interface SiegeDamageResult {
  /** Actual amount subtracted from HP (after shield absorption and armor reduction) — 0 if the shield fully absorbed the hit. */
  damageToHp: number;
  /** True the instant this hit brought the tower's HP to exactly 0 (was above 0 before). */
  towerJustDisabled: boolean;
}

/**
 * Resolves one Boss Siege Attack hit against `tower` — shield absorbs
 * first, armor reduces what's left, remainder comes off HP. Reaching 0 HP
 * disables the tower (reuses the exact same disabledRemainingMs mechanic a
 * DISABLER enemy already uses) for `disableDurationMs` rather than
 * destroying it — a tower is never permanently lost to this.
 */
export function applySiegeDamage(tower: TowerInstance, rawDamage: number, disableDurationMs: number): SiegeDamageResult {
  const def = getTowerSurvivalDefinition(tower.type);
  let remaining = rawDamage;

  if (tower.shieldHp > 0) {
    const absorbed = Math.min(tower.shieldHp, remaining);
    tower.shieldHp -= absorbed;
    remaining -= absorbed;
  }

  const afterArmor = remaining * (1 - def.armor);
  const wasAboveZero = tower.hp > 0;
  tower.hp = Math.max(0, tower.hp - afterArmor);
  const towerJustDisabled = wasAboveZero && tower.hp === 0;
  if (towerJustDisabled) disableTower(tower, disableDurationMs);

  return { damageToHp: afterArmor, towerJustDisabled };
}

/**
 * The single choke point every combat call site reads a tower's effective
 * damage/attack-speed/range from (CombatSystem.ts's resolveNormalAttack,
 * resolveSpecialAttack, and every chain/crit/frozen-bonus damage
 * calculation) — which is exactly why layering Mastery's bonus multiplier
 * here, rather than in each of those call sites individually, is both the
 * lowest-risk integration AND the one place it can never be forgotten for
 * a future combat formula. See config/towerMastery.ts for why this stays a
 * uniform multiplier rather than touching any tower's identity-defining
 * special (crit/burn/freeze/chain) formulas.
 */
export function getTowerStats(tower: TowerInstance): TowerLevelStats {
  const levelStats = getTowerLevelStats(tower.type, tower.level);
  if (tower.masteryLevel <= 0) return levelStats;
  const mastery = getMasteryBonusMultipliers(tower.masteryLevel);
  return {
    ...levelStats,
    damage: round2(levelStats.damage * mastery.damage),
    attackSpeed: round2(levelStats.attackSpeed * mastery.attackSpeed),
    range: round2(levelStats.range * mastery.range),
  };
}

function round2(value: number): number {
  return Math.round(value * 100) / 100;
}

// ---------------------------------------------------------------------------
// Master Implementation Pass spec sections 3-6 — Tower Mastery.
// ---------------------------------------------------------------------------

/** Always purchasable — no max level (spec: "SEM CAP REAL"). */
export function canUpgradeMastery(): boolean {
  return true;
}

export function getMasteryUpgradeCostFor(tower: TowerInstance): number {
  return getMasteryUpgradeCost(tower.type, tower.masteryLevel);
}

/** Mutates `tower` in place, incrementing its mastery level (caller owns gold deduction, exactly like upgradeTower above). */
export function upgradeMastery(tower: TowerInstance): void {
  tower.masteryLevel += 1;
}

export function canUpgradeTower(tower: TowerInstance): boolean {
  return tower.level < MAX_TOWER_LEVEL;
}

export function getTowerUpgradeCost(tower: TowerInstance): number | null {
  return getUpgradeCost(tower.type, tower.level);
}

/** Mutates `tower` in place, incrementing its level (caller owns gold deduction). */
export function upgradeTower(tower: TowerInstance): void {
  if (canUpgradeTower(tower)) tower.level += 1;
}

/** Mutates `tower` in place, ticking its attack cooldown, special cooldown, and any active jam down. */
export function tickTowerCooldown(tower: TowerInstance, dtMs: number): void {
  tower.cooldownRemainingMs = Math.max(0, tower.cooldownRemainingMs - dtMs);
  tower.specialCooldownRemainingMs = Math.max(0, tower.specialCooldownRemainingMs - dtMs);
  tower.disabledRemainingMs = Math.max(0, tower.disabledRemainingMs - dtMs);
}

export function isTowerReadyToAttack(tower: TowerInstance): boolean {
  return tower.cooldownRemainingMs <= 0 && tower.disabledRemainingMs <= 0;
}

/** Special Attack readiness — completely independent of the normal-attack cooldown above; only shares the disable-jam gate (a disabled tower can't fire either attack). */
export function isTowerReadyForSpecial(tower: TowerInstance): boolean {
  return tower.specialCooldownRemainingMs <= 0 && tower.disabledRemainingMs <= 0;
}

/** Jams the tower for `durationMs` (a DISABLER-archetype hit) — refreshes rather than stacks. */
export function disableTower(tower: TowerInstance, durationMs: number): void {
  tower.disabledRemainingMs = Math.max(tower.disabledRemainingMs, durationMs);
}

/** Resets the cooldown based on the tower's current attack speed (attacks/second). */
export function resetTowerCooldown(tower: TowerInstance): void {
  const stats = getTowerStats(tower);
  tower.cooldownRemainingMs = 1000 / stats.attackSpeed;
}

/** Resets the Special Attack cooldown to its fixed per-tower-type interval (config/towerSpecials.ts) — never derived from attackSpeed/level. */
export function resetTowerSpecialCooldown(tower: TowerInstance): void {
  tower.specialCooldownRemainingMs = getTowerSpecialCooldownMs(tower.type);
}

// ---------------------------------------------------------------------------
// Progression 2.0 — Specialization / Upgrade Slot.
// ---------------------------------------------------------------------------

export function canChooseSpecialization(tower: TowerInstance): boolean {
  return tower.specializationId === null && tower.level >= SPECIALIZATION_UNLOCK_TOWER_LEVEL;
}

/** Mutates `tower` in place. A no-op if a specialization is already chosen, the tower isn't high enough level yet, or `id` doesn't belong to this tower's type. Caller owns gold deduction (choosing costs the level-0->1 specialization price). */
export function chooseSpecialization(tower: TowerInstance, id: SpecializationId): boolean {
  if (!canChooseSpecialization(tower)) return false;
  if (!isSpecializationForTower(id, tower.type)) return false;
  tower.specializationId = id;
  tower.specializationLevel = 1;
  return true;
}

export function canUpgradeSpecialization(tower: TowerInstance): boolean {
  return tower.specializationId !== null && tower.specializationLevel < MAX_SPECIALIZATION_LEVEL;
}

export function getSpecializationUpgradeCostFor(tower: TowerInstance): number | null {
  if (!tower.specializationId) return null;
  return getSpecializationUpgradeCost(tower.type, tower.specializationLevel);
}

/** Mutates `tower` in place, incrementing its specialization level (caller owns gold deduction). */
export function upgradeSpecialization(tower: TowerInstance): void {
  if (canUpgradeSpecialization(tower)) tower.specializationLevel += 1;
}

// ---------------------------------------------------------------------------
// Progression 2.0 — Skins (cosmetic only, never read by combat code).
// ---------------------------------------------------------------------------

/**
 * SEASON-RESET-CORRECTION — skin ownership, not live tower level, is the
 * gate. Tower level is Season-scoped (resets to 0 every Season), but a skin
 * bought/unlocked with real Gems must stay equippable forever afterward
 * (spec example: "Skin Astral" unlocked at Lv15 in Season 1 stays equippable
 * in Season 2 even though the tower is back at level 0). `ownedSkinIds` is
 * the permanent SaveData.ownedTowerSkinIds set — see GameEngine for how a
 * skin actually enters it (getNewlyUnlockedSkinIds below).
 */
export function canEquipSkin(tower: TowerInstance, skinId: string, ownedSkinIds: ReadonlySet<string>): boolean {
  const def = getTowerSkinDefinition(skinId);
  return !!def && def.towerType === tower.type && ownedSkinIds.has(skinId);
}

/** Mutates `tower` in place. `skinId` of null clears back to the default look. Purely cosmetic — never touches level/specialization/stats. */
export function equipSkin(tower: TowerInstance, skinId: string | null, ownedSkinIds: ReadonlySet<string>): boolean {
  if (skinId === null) {
    tower.equippedSkinId = null;
    return true;
  }
  if (!canEquipSkin(tower, skinId, ownedSkinIds)) return false;
  tower.equippedSkinId = skinId;
  return true;
}

/**
 * Whether `skinId` is currently purchasable for `tower` — reached the
 * required level (this Season or a prior one; level itself doesn't persist,
 * but the fact that a tower of this type has been leveled enough IS
 * re-earnable every Season) and not already owned. Caller (GameEngine)
 * still owns checking/deducting Gems — see towerSkins.ts's gemCost.
 */
export function canPurchaseSkin(tower: TowerInstance, skinId: string, ownedSkinIds: ReadonlySet<string>): boolean {
  const def = getTowerSkinDefinition(skinId);
  return !!def && def.towerType === tower.type && tower.level >= def.unlockLevel && !ownedSkinIds.has(skinId);
}
