import {
  getTowerLevelStats,
  getUpgradeCost,
  MAX_TOWER_LEVEL,
  type TowerLevelStats,
  type TowerType,
} from "@/config/towerStats";
import {
  getSpecializationUpgradeCost,
  isSpecializationForTower,
  MAX_SPECIALIZATION_LEVEL,
  SPECIALIZATION_UNLOCK_TOWER_LEVEL,
  type SpecializationId,
} from "@/config/specializations";
import { getTowerSkinDefinition } from "@/config/towerSkins";
import { getTowerSpecialCooldownMs } from "@/config/towerSpecials";
import { getMasteryBonusMultipliers, getMasteryUpgradeCost } from "@/config/towerMastery";
import type { Vector2 } from "@/utils/geometry";

export interface TowerInstance {
  id: string;
  slotId: string;
  type: TowerType;
  level: number;
  position: Vector2;
  cooldownRemainingMs: number;
  /**
   * Master Implementation spec section 26-28 — Special Attack: a SECOND,
   * fully independent cooldown timer from `cooldownRemainingMs`. The normal
   * attack keeps firing at its attack-speed-driven cadence exactly as
   * before; this one ticks down on a fixed per-tower-type interval (see
   * config/towerSpecials.ts) and fires a distinct, more impactful attack
   * when it reaches 0, without ever touching or resetting the normal
   * cooldown. Deliberately NOT derived from attackSpeed — it's a rhythm of
   * its own, the way a real "ultimate" reads differently from a basic
   * attack.
   */
  specialCooldownRemainingMs: number;
  /** >0 while jammed by a DISABLER-archetype enemy/mini-boss — see CombatSystem.tickEnemyDisableAbilities. */
  disabledRemainingMs: number;
  /** Progression 2.0 — the player's chosen build-identity path, null until chosen. Permanent once set (see chooseSpecialization). */
  specializationId: SpecializationId | null;
  /** 0 = not chosen yet. 1..MAX_SPECIALIZATION_LEVEL once chosen — a second, independent gold-sink track from the tower's own level. */
  specializationLevel: number;
  /** Progression 2.0 — cosmetic-only equipped skin id, or null for the default look. Never read by combat code. */
  equippedSkinId: string | null;
  /** Master Implementation Pass spec section 4-6 — TOWER MASTERY: an uncapped, independent gold-sink track past MAX_TOWER_LEVEL. 0 = never invested. See config/towerMastery.ts for the bonus/cost formulas. */
  masteryLevel: number;
}

/**
 * Persistent shape of a tower — what survives across attempts/reloads in
 * SaveData. Deliberately excludes runtime-only fields (id, position,
 * cooldown) that get regenerated by `createTowerInstance` on resume.
 */
export interface TowerLoadoutEntry {
  slotId: string;
  type: TowerType;
  level: number;
  /** Optional so existing fixtures/tests written before Progression 2.0 still typecheck — SaveSystem.parseTowerLoadout and GameEngine.persist() always populate these on real data. */
  specializationId?: SpecializationId | null;
  specializationLevel?: number;
  equippedSkinId?: string | null;
  /** Optional for the same reason as the specialization fields above — self-heals to 0 on load for a save written before Mastery existed. */
  masteryLevel?: number;
}

let nextTowerId = 1;

export function createTowerInstance(
  slotId: string,
  type: TowerType,
  position: Vector2,
  initialLevel = 1,
  specializationId: SpecializationId | null = null,
  specializationLevel = 0,
  equippedSkinId: string | null = null,
  masteryLevel = 0,
): TowerInstance {
  return {
    id: `tower-${nextTowerId++}`,
    slotId,
    type,
    level: Math.min(Math.max(initialLevel, 1), MAX_TOWER_LEVEL),
    position,
    cooldownRemainingMs: 0,
    // A freshly-built tower must charge up before its first Special Attack
    // — the ultimate meter starts empty, not full — both thematically (an
    // "ultimate" firing before a single normal shot feels wrong) and
    // mechanically (keeps the special's much bigger cooldown from ever
    // colliding with the normal attack's own instant-ready-at-0 on the
    // very same first tick).
    specialCooldownRemainingMs: getTowerSpecialCooldownMs(type),
    disabledRemainingMs: 0,
    specializationId,
    specializationLevel,
    equippedSkinId,
    masteryLevel,
  };
}

/**
 * The single choke point every combat call site reads a tower's effective
 * damage/attack-speed/range from (CombatSystem.ts's resolveNormalAttack,
 * resolveSpecialAttack, and every chain/crit/frozen-bonus damage
 * calculation) — which is exactly why layering Mastery's bonus multiplier
 * here, rather than in each of those call sites individually, is both the
 * lowest-risk integration AND the one place it can never be forgotten for
 * a future combat formula. See config/towerMastery.ts for why this stays a
 * uniform multiplier rather than touching any tower's identity-defining
 * special (crit/burn/freeze/chain) formulas.
 */
export function getTowerStats(tower: TowerInstance): TowerLevelStats {
  const levelStats = getTowerLevelStats(tower.type, tower.level);
  if (tower.masteryLevel <= 0) return levelStats;
  const mastery = getMasteryBonusMultipliers(tower.masteryLevel);
  return {
    ...levelStats,
    damage: round2(levelStats.damage * mastery.damage),
    attackSpeed: round2(levelStats.attackSpeed * mastery.attackSpeed),
    range: round2(levelStats.range * mastery.range),
  };
}

function round2(value: number): number {
  return Math.round(value * 100) / 100;
}

// ---------------------------------------------------------------------------
// Master Implementation Pass spec sections 3-6 — Tower Mastery.
// ---------------------------------------------------------------------------

/** Always purchasable — no max level (spec: "SEM CAP REAL"). */
export function canUpgradeMastery(): boolean {
  return true;
}

export function getMasteryUpgradeCostFor(tower: TowerInstance): number {
  return getMasteryUpgradeCost(tower.type, tower.masteryLevel);
}

/** Mutates `tower` in place, incrementing its mastery level (caller owns gold deduction, exactly like upgradeTower above). */
export function upgradeMastery(tower: TowerInstance): void {
  tower.masteryLevel += 1;
}

export function canUpgradeTower(tower: TowerInstance): boolean {
  return tower.level < MAX_TOWER_LEVEL;
}

export function getTowerUpgradeCost(tower: TowerInstance): number | null {
  return getUpgradeCost(tower.type, tower.level);
}

/** Mutates `tower` in place, incrementing its level (caller owns gold deduction). */
export function upgradeTower(tower: TowerInstance): void {
  if (canUpgradeTower(tower)) tower.level += 1;
}

/** Mutates `tower` in place, ticking its attack cooldown, special cooldown, and any active jam down. */
export function tickTowerCooldown(tower: TowerInstance, dtMs: number): void {
  tower.cooldownRemainingMs = Math.max(0, tower.cooldownRemainingMs - dtMs);
  tower.specialCooldownRemainingMs = Math.max(0, tower.specialCooldownRemainingMs - dtMs);
  tower.disabledRemainingMs = Math.max(0, tower.disabledRemainingMs - dtMs);
}

export function isTowerReadyToAttack(tower: TowerInstance): boolean {
  return tower.cooldownRemainingMs <= 0 && tower.disabledRemainingMs <= 0;
}

/** Special Attack readiness — completely independent of the normal-attack cooldown above; only shares the disable-jam gate (a disabled tower can't fire either attack). */
export function isTowerReadyForSpecial(tower: TowerInstance): boolean {
  return tower.specialCooldownRemainingMs <= 0 && tower.disabledRemainingMs <= 0;
}

/** Jams the tower for `durationMs` (a DISABLER-archetype hit) — refreshes rather than stacks. */
export function disableTower(tower: TowerInstance, durationMs: number): void {
  tower.disabledRemainingMs = Math.max(tower.disabledRemainingMs, durationMs);
}

/** Resets the cooldown based on the tower's current attack speed (attacks/second). */
export function resetTowerCooldown(tower: TowerInstance): void {
  const stats = getTowerStats(tower);
  tower.cooldownRemainingMs = 1000 / stats.attackSpeed;
}

/** Resets the Special Attack cooldown to its fixed per-tower-type interval (config/towerSpecials.ts) — never derived from attackSpeed/level. */
export function resetTowerSpecialCooldown(tower: TowerInstance): void {
  tower.specialCooldownRemainingMs = getTowerSpecialCooldownMs(tower.type);
}

// ---------------------------------------------------------------------------
// Progression 2.0 — Specialization / Upgrade Slot.
// ---------------------------------------------------------------------------

export function canChooseSpecialization(tower: TowerInstance): boolean {
  return tower.specializationId === null && tower.level >= SPECIALIZATION_UNLOCK_TOWER_LEVEL;
}

/** Mutates `tower` in place. A no-op if a specialization is already chosen, the tower isn't high enough level yet, or `id` doesn't belong to this tower's type. Caller owns gold deduction (choosing costs the level-0->1 specialization price). */
export function chooseSpecialization(tower: TowerInstance, id: SpecializationId): boolean {
  if (!canChooseSpecialization(tower)) return false;
  if (!isSpecializationForTower(id, tower.type)) return false;
  tower.specializationId = id;
  tower.specializationLevel = 1;
  return true;
}

export function canUpgradeSpecialization(tower: TowerInstance): boolean {
  return tower.specializationId !== null && tower.specializationLevel < MAX_SPECIALIZATION_LEVEL;
}

export function getSpecializationUpgradeCostFor(tower: TowerInstance): number | null {
  if (!tower.specializationId) return null;
  return getSpecializationUpgradeCost(tower.type, tower.specializationLevel);
}

/** Mutates `tower` in place, incrementing its specialization level (caller owns gold deduction). */
export function upgradeSpecialization(tower: TowerInstance): void {
  if (canUpgradeSpecialization(tower)) tower.specializationLevel += 1;
}

// ---------------------------------------------------------------------------
// Progression 2.0 — Skins (cosmetic only, never read by combat code).
// ---------------------------------------------------------------------------

export function canEquipSkin(tower: TowerInstance, skinId: string): boolean {
  const def = getTowerSkinDefinition(skinId);
  return !!def && def.towerType === tower.type && tower.level >= def.unlockLevel;
}

/** Mutates `tower` in place. `skinId` of null clears back to the default look. Purely cosmetic — never touches level/specialization/stats. */
export function equipSkin(tower: TowerInstance, skinId: string | null): boolean {
  if (skinId === null) {
    tower.equippedSkinId = null;
    return true;
  }
  if (!canEquipSkin(tower, skinId)) return false;
  tower.equippedSkinId = skinId;
  return true;
}
